/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program;

import java.awt.Color;
import java.util.Set;

/**
 *
 * @author SzabóRoland(SZF_2023
 */
public class BabGUI extends javax.swing.JFrame implements EI.BBListener{

    /**
     * Creates new form BabGUI
     */
    public BabGUI() {
        initComponents();
        Bab.Jatek.addListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Bt_ujrakezd = new javax.swing.JButton();
        Bt_vesz = new javax.swing.JButton();
        La_osszbab = new javax.swing.JLabel();
        La_babjaim = new javax.swing.JLabel();
        La_babjai = new javax.swing.JLabel();
        JSp_menny = new javax.swing.JSpinner();
        La_SignBabjai = new javax.swing.JLabel();
        La_SignBabjaim = new javax.swing.JLabel();
        La_kinyert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Feladat: Vedd el az utolsó babot!");

        Bt_ujrakezd.setText("Újrakezdés");
        Bt_ujrakezd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ujrakezdActionPerformed(evt);
            }
        });

        Bt_vesz.setText("Vesz");

        La_osszbab.setText("Babok");

        La_babjaim.setText("Babjaim");

        La_babjai.setText("Babjai");

        La_SignBabjai.setBackground(new java.awt.Color(0, 153, 0));
        La_SignBabjai.setMaximumSize(new java.awt.Dimension(16, 16));
        La_SignBabjai.setMinimumSize(new java.awt.Dimension(16, 16));
        La_SignBabjai.setOpaque(true);
        La_SignBabjai.setPreferredSize(new java.awt.Dimension(16, 16));

        La_SignBabjaim.setBackground(new java.awt.Color(0, 153, 0));
        La_SignBabjaim.setMaximumSize(new java.awt.Dimension(16, 16));
        La_SignBabjaim.setMinimumSize(new java.awt.Dimension(16, 16));
        La_SignBabjaim.setOpaque(true);
        La_SignBabjaim.setPreferredSize(new java.awt.Dimension(16, 16));

        La_kinyert.setBackground(new java.awt.Color(153, 102, 0));
        La_kinyert.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(La_osszbab)
                .addGap(248, 248, 248))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(La_SignBabjaim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Bt_ujrakezd)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(La_SignBabjai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(Bt_vesz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JSp_menny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(La_kinyert, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(La_babjaim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(La_babjai)))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(La_SignBabjai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(La_SignBabjaim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(La_osszbab)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(La_babjaim)
                            .addComponent(La_babjai))
                        .addGap(14, 14, 14)
                        .addComponent(Bt_ujrakezd)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_vesz))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JSp_menny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(La_kinyert, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_ujrakezdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ujrakezdActionPerformed
        Bab.Jatek.Restart();
    }//GEN-LAST:event_Bt_ujrakezdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BabGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BabGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_ujrakezd;
    private javax.swing.JButton Bt_vesz;
    private javax.swing.JSpinner JSp_menny;
    private javax.swing.JLabel La_SignBabjai;
    private javax.swing.JLabel La_SignBabjaim;
    private javax.swing.JLabel La_babjai;
    private javax.swing.JLabel La_babjaim;
    private javax.swing.JLabel La_kinyert;
    private javax.swing.JLabel La_osszbab;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void adatFrissites() {
        La_SignBabjai.setBackground(Color.red);
        La_SignBabjaim.setBackground(Color.green);
        
    }

    @Override
    public void valakiNyert() {
        La_kinyert.setText(Bab.Jatek.kinyert+"");
    }
}
